### ISSUE TITLE
An Issue for not using MICA2 in PyPETaL v1.0.0

### ISSUE THREAD

**Issue by YuanzheJiang** [Zstone19/pypetal#27]
If I want use PyPETaL withthout MICA, I will get an error telling me " 'NoneType' object has no attribute 'bcast' ". I guess it is because you set `comm=None` if MICA2 doesn't exist. So I think you perhaps need to put lines 319-324 in `pypetal/pipeline.py` after `if run_mica2`.

**Comment by Zstone19** [comment]
Yep, didn't notice that bug. Should be working fine now!
